services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    restart: on-failure:0
    ports:
    - 8080:8080
    - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      CLUSTER_HOSTNAME: 'node1'